Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data type of variables list_ and array_list. list_ is likely a Python list, while array_list is presumably a NumPy array. You can use the type() function to check the data types.

In [1]:
import numpy as np

list_ = [1, 2, 3, 4, 5]
array_list = np.array(list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [2]:
for element in list_:
    print("Data type of element in list_:", type(element))

for element in array_list:
    print("Data type of element in array_list:", element.dtype)


Data type of element in list_: <class 'int'>
Data type of element in list_: <class 'int'>
Data type of element in list_: <class 'int'>
Data type of element in list_: <class 'int'>
Data type of element in list_: <class 'int'>
Data type of element in array_list: int64
Data type of element in array_list: int64
Data type of element in array_list: int64
Data type of element in array_list: int64
Data type of element in array_list: int64


Q3. Considering the following changes in the variable array_list:

In [3]:
array_list = np.array(object=list_, dtype=int)


Yes, there will be a difference in the data type of the elements present in both the variables list_ and array_list. All the elements in array_list will be explicitly converted to the int data type. To print the data types of each element, you can modify the code in the previous answer.

Q4. Write a code to find the following characteristics of variable, num_array: (i) shape (ii) size

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create a numpy array of a 3x3 matrix containing zeros only, using a numpy array creation function.

In [5]:
import numpy as np

zero_array = np.zeros((3, 3))
print("Zero array:\n", zero_array)


Zero array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5, 5) using numpy functions?

In [6]:
import numpy as np

identity_matrix = np.eye(5)
print("Identity matrix:\n", identity_matrix)


Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
